<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Cors" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.4" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.WebEncoders" Version="10.0.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Quick.AspNetCore.Components.Web.Extensions" Version="6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="wwwroot\sample-data\weather.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FarmApp.Components\FarmApp.Components.csproj" />
    <ProjectReference Include="..\FarmApp.Services\FarmApp.Services.csproj" />
    <ProjectReference Include="..\..\FarmApp.Shared\FarmApp.Shared.csproj" />
  </ItemGroup>

</Project>
