<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <Title>Bch.Modules.Themes</Title>
        <Authors>VertexCode</Authors>
        <Description>A modern Blazor component set focused on performance and flexibility—original components with rich customization</Description>
        <Company>VertexCode</Company>
        <RootNamespace>Bch.Modules.Themes</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.4"/>
    </ItemGroup>
</Project>
