// <auto-generated />
using System;
using System.Collections.Generic;
using FarmApp.DataAccessLayer.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FarmApp.DataAccessLayer.Migrations
{
    [DbContext(typeof(FarmAppDbContext))]
    partial class FarmAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FarmApp.Entities.Entity.CategoryEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.CustomSteadEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteadId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SteadId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomSteads");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.NotificationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateTimeOfSend")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NotificationKind")
                        .HasColumnType("integer");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeOfSend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeOfTargetUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeUrlForRedirection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlForRedirection")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.OwnershipEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ownerships");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyAndSteadEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CustomSteadId")
                        .HasColumnType("text");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SteadId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomSteadId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("SteadId");

                    b.ToTable("PropertyAndSteads");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("MultipolygonSerialized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyNoteEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("NotifyBeforeEnd")
                        .HasColumnType("integer");

                    b.Property<int?>("NotifyBeforeStart")
                        .HasColumnType("integer");

                    b.Property<string>("PreviewMediaId")
                        .HasColumnType("text");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("StatusId");

                    b.ToTable("PropertyNotes");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyNoteMedia", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MediaType")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyNoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyNoteId");

                    b.ToTable("PropertyNoteMedia");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyNoteStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BGColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextColorHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PropertyNoteStatusEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BGColorHex = "#DCFAE9",
                            Code = "FAILED",
                            IsDefault = true,
                            Name = "Не виконано",
                            TextColorHex = "#1D8B41"
                        },
                        new
                        {
                            Id = 2,
                            BGColorHex = "#FDF2CA",
                            Code = "IN_PROGRESS",
                            IsDefault = true,
                            Name = "В процессі",
                            TextColorHex = "#925C00"
                        },
                        new
                        {
                            Id = 3,
                            BGColorHex = "#C42921",
                            Code = "DONE",
                            IsDefault = true,
                            Name = "Виконано",
                            TextColorHex = "#FFDED8"
                        });
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PurposeEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Purposes");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PushDeviceRegistrationEntity", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("DeviceId");

                    b.ToTable("push_device_registrations");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PushNotificationQueueEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("PropertyNoteId")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyNoteId");

                    b.HasIndex("Status", "SendAt");

                    b.ToTable("PushNotificationsQueue");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.SteadEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Area")
                        .HasColumnType("real");

                    b.Property<string>("AreaUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CadNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnershipId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurposeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnershipId");

                    b.HasIndex("PurposeId");

                    b.ToTable("Steads");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailConfirmToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmailVerificationCode")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("IconNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiration")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenLifeTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<double?>("SelectedLocationLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("SelectedLocationLongitude")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationSentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.UserNotificationPreferencesEntity", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<bool>("ActivityRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("InAppNotificationsOnly")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificationsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("SystemNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeatherAlertsEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("user_notification_preferences");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.CustomSteadEntity", b =>
                {
                    b.HasOne("FarmApp.Entities.Entity.SteadEntity", "Stead")
                        .WithMany()
                        .HasForeignKey("SteadId");

                    b.HasOne("FarmApp.Entities.Entity.UserEntity", "User")
                        .WithMany("CustomSteads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stead");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyAndSteadEntity", b =>
                {
                    b.HasOne("FarmApp.Entities.Entity.CustomSteadEntity", "CustomStead")
                        .WithMany()
                        .HasForeignKey("CustomSteadId");

                    b.HasOne("FarmApp.Entities.Entity.PropertyEntity", "Property")
                        .WithMany("PropertySteads")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmApp.Entities.Entity.SteadEntity", "Stead")
                        .WithMany()
                        .HasForeignKey("SteadId");

                    b.Navigation("CustomStead");

                    b.Navigation("Property");

                    b.Navigation("Stead");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyEntity", b =>
                {
                    b.HasOne("FarmApp.Entities.Entity.UserEntity", "User")
                        .WithMany("Properties")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyNoteEntity", b =>
                {
                    b.HasOne("FarmApp.Entities.Entity.PropertyEntity", "Property")
                        .WithMany("PropertyNotes")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmApp.Entities.Entity.PropertyNoteStatusEntity", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Property");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyNoteMedia", b =>
                {
                    b.HasOne("FarmApp.Entities.Entity.PropertyNoteEntity", "PropertyNote")
                        .WithMany("Medias")
                        .HasForeignKey("PropertyNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyNote");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.SteadEntity", b =>
                {
                    b.HasOne("FarmApp.Entities.Entity.CategoryEntity", "Category")
                        .WithMany("Steads")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmApp.Entities.Entity.OwnershipEntity", "Ownership")
                        .WithMany("Steads")
                        .HasForeignKey("OwnershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FarmApp.Entities.Entity.PurposeEntity", "Purpose")
                        .WithMany("Steads")
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Ownership");

                    b.Navigation("Purpose");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.UserNotificationPreferencesEntity", b =>
                {
                    b.HasOne("FarmApp.Entities.Entity.UserEntity", "User")
                        .WithOne("NotificationPreferences")
                        .HasForeignKey("FarmApp.Entities.Entity.UserNotificationPreferencesEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.CategoryEntity", b =>
                {
                    b.Navigation("Steads");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.OwnershipEntity", b =>
                {
                    b.Navigation("Steads");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyEntity", b =>
                {
                    b.Navigation("PropertyNotes");

                    b.Navigation("PropertySteads");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PropertyNoteEntity", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.PurposeEntity", b =>
                {
                    b.Navigation("Steads");
                });

            modelBuilder.Entity("FarmApp.Entities.Entity.UserEntity", b =>
                {
                    b.Navigation("CustomSteads");

                    b.Navigation("NotificationPreferences");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
